import { Button } from "@/components/ui/button";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import React from "react";

const DealerAddEditModal = ({
  open,
  cleanupTempFiles,
  setOpen,
  resetModalForm,
  editing,
  onSubmit,
  form,
  setForm,
  modalZone,
  onModalZoneChange,
  NONE,
  zones,
  modalRegion,
  onModalRegionChange,
  regions,
  modalArea,
  onModalAreaChange,
  areas,
  territories,
  warehouses,
  users,
  setRequiredAttachment,
  filePreview,
  addOptionalFiles,
  removeOptionalAttachment,
}) => {
  return (
    <>
      {/* Dealer Modal */}
      <Dialog
        open={open}
        onOpenChange={async (v) => {
          if (!v) {
            // modal closed without saving -> cleanup temp files
            await cleanupTempFiles();
            resetModalForm();
          }
          setOpen(v);
        }}
      >
        <DialogContent
          className="
            !w-full 
            !max-w-[95vw] 
            max-h-[90vh] 
            overflow-y-auto 
            p-0 
            rounded-xl 
            shadow-2xl 
            bg-background
            border
          "
        >
          {/* Sticky Header */}
          <div className="sticky top-0 z-20 bg-background border-b px-6 py-4 flex items-center justify-between">
            <h3 className="text-xl font-semibold">
              {editing ? "Edit Dealer" : "New Dealer"}
            </h3>
            {editing?._id && (
              <div className="text-xs text-muted-foreground">
                ID: {editing._id}
              </div>
            )}
          </div>

          {/* FormBody */}
          <form onSubmit={onSubmit} className="px-6 py-6 space-y-8">
            {/* Basic Info */}
            <div className="space-y-4">
              <h4 className="text-sm font-semibold text-muted-foreground">
                Basic Information
              </h4>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                {/* LEFT */}
                <div className="space-y-3">
                  <div>
                    <label className="text-sm">Name</label>
                    <Input
                      value={form.name}
                      onChange={(e) =>
                        setForm({ ...form, name: e.target.value })
                      }
                    />
                  </div>

                  <div>
                    <label className="text-sm">Code (auto)</label>
                    <Input
                      value={form.code || ""}
                      readOnly
                      placeholder="Auto-generated by server"
                    />
                  </div>

                  <div>
                    <label className="text-sm">Proprietor</label>
                    <Input
                      value={form.proprietor}
                      onChange={(e) =>
                        setForm({ ...form, proprietor: e.target.value })
                      }
                    />
                  </div>

                  {/* ZONE → TERRITORY */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <div>
                      <label className="text-sm">Zone</label>
                      <Select
                        value={modalZone}
                        onValueChange={onModalZoneChange}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select Zone" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value={NONE}>Choose Zone</SelectItem>
                          {zones.map((z) => (
                            <SelectItem key={z._id} value={z._id}>
                              {z.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div>
                      <label className="text-sm">Region</label>
                      <Select
                        value={modalRegion}
                        onValueChange={onModalRegionChange}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select Region" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value={NONE}>Choose Region</SelectItem>
                          {regions.map((r) => (
                            <SelectItem key={r._id} value={r._id}>
                              {r.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div>
                      <label className="text-sm">Area</label>
                      <Select
                        value={modalArea}
                        onValueChange={onModalAreaChange}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select Area" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value={NONE}>Choose Area</SelectItem>
                          {areas.map((a) => (
                            <SelectItem key={a._id} value={a._id}>
                              {a.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div>
                      <label className="text-sm">Territory</label>
                      <Select
                        value={form.territory || NONE}
                        onValueChange={(v) =>
                          setForm({ ...form, territory: v === NONE ? "" : v })
                        }
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select Territory" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value={NONE}>Choose Territory</SelectItem>
                          {territories.map((t) => (
                            <SelectItem key={t._id} value={t._id}>
                              {t.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div>
                    <label className="text-sm">Type</label>
                    <Select
                      value={form.type || NONE}
                      onValueChange={(v) =>
                        setForm({ ...form, type: v === NONE ? "" : v })
                      }
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Dealer Type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value={NONE}>Select Type</SelectItem>
                        <SelectItem value="Credit">Credit</SelectItem>
                        <SelectItem value="Cash">Cash</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-sm">Credit Limit</label>
                      <Input
                        value={String(form.creditLimit ?? "")}
                        onChange={(e) =>
                          setForm({ ...form, creditLimit: e.target.value })
                        }
                      />
                    </div>

                    <div>
                      <label className="text-sm">Opening Balance</label>
                      <Input
                        value={String(form.openingBalance ?? "")}
                        onChange={(e) =>
                          setForm({ ...form, openingBalance: e.target.value })
                        }
                      />
                    </div>
                  </div>

                  <div>
                    <label className="text-sm">Email</label>
                    <Input
                      value={form.email}
                      onChange={(e) =>
                        setForm({ ...form, email: e.target.value })
                      }
                    />
                  </div>

                  <div>
                    <label className="text-sm">Address</label>
                    <Input
                      value={form.address}
                      onChange={(e) =>
                        setForm({ ...form, address: e.target.value })
                      }
                    />
                  </div>
                </div>

                {/* RIGHT column */}
                <div className="space-y-3">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <div>
                      <label className="text-sm">Op. Date</label>
                      <Input
                        type="date"
                        value={form.opDate}
                        onChange={(e) =>
                          setForm({ ...form, opDate: e.target.value })
                        }
                      />
                    </div>

                    <div>
                      <label className="text-sm">Op. Month</label>
                      <Input
                        value={form.opMonth}
                        onChange={(e) =>
                          setForm({ ...form, opMonth: e.target.value })
                        }
                      />
                    </div>

                    <div>
                      <label className="text-sm">
                        Last Purchase Date (optional)
                      </label>
                      <Input
                        type="date"
                        value={form.lastPurchaseDate}
                        onChange={(e) =>
                          setForm({ ...form, lastPurchaseDate: e.target.value })
                        }
                      />
                    </div>
                  </div>

                  <div>
                    <label className="text-sm">Warehouse</label>
                    <Select
                      value={form.warehouse || NONE}
                      onValueChange={(v) =>
                        setForm({ ...form, warehouse: v === NONE ? "" : v })
                      }
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select Warehouse" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value={NONE}>No Warehouse</SelectItem>
                        {warehouses.map((w) => (
                          <SelectItem key={w._id} value={w._id}>
                            {w.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <label className="text-sm">Assigned Sales Manager</label>
                    <Select
                      value={form.assignedSalesManager || NONE}
                      onValueChange={(v) =>
                        setForm({
                          ...form,
                          assignedSalesManager: v === NONE ? "" : v,
                        })
                      }
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select Manager" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value={NONE}>None</SelectItem>
                        {users.map((u) => (
                          <SelectItem key={u._id} value={u._id}>
                            {u.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <label className="text-sm">Status</label>
                    <Select
                      value={form.status || NONE}
                      onValueChange={(v) =>
                        setForm({ ...form, status: v === NONE ? "" : v })
                      }
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Status" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value={NONE}>Select Status</SelectItem>
                        <SelectItem value="pending">Pending</SelectItem>
                        <SelectItem value="active">Active</SelectItem>
                        <SelectItem value="inactive">Inactive</SelectItem>
                        <SelectItem value="suspended">Suspended</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <label className="text-sm">Notes</label>
                    <textarea
                      value={form.notes}
                      onChange={(e) =>
                        setForm({ ...form, notes: e.target.value })
                      }
                      className="w-full border rounded p-2 min-h-[96px] resize-vertical"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* PHONE */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <label className="text-sm font-semibold">Phone</label>
              </div>

              <div className="flex gap-3 items-center">
                <Input
                  value={form.phoneNumber}
                  onChange={(e) =>
                    setForm({ ...form, phoneNumber: e.target.value })
                  }
                />
              </div>
            </div>

            {/* Attachments */}
            <div className="space-y-4">
              <h4 className="text-sm font-semibold">Attachments</h4>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Required attachments (single each) */}
                <div>
                  <div className="mb-2 font-medium">Required</div>

                  {(
                    [
                      { key: "bankCheque", label: "Bank Cheque" },
                      { key: "tradeLicense", label: "Trade License" },
                      { key: "nidCard", label: "NID Card" },
                      { key: "informationDeed", label: "Information / Deed" },
                      { key: "pesticideLicense", label: "Pesticide License" },
                    ] as { key: keyof Attachments["required"]; label: string }[]
                  ).map((it) => {
                    const url = form.attachments?.required?.[it.key];
                    return (
                      <div key={it.key} className="mb-3">
                        <div className="flex items-center justify-between mb-1">
                          <div className="text-sm">{it.label}</div>
                          <div className="text-xs text-muted-foreground">
                            required
                          </div>
                        </div>

                        <div className="flex items-center gap-3">
                          <label className="inline-flex items-center gap-2 cursor-pointer">
                            <input
                              type="file"
                              accept="image/*,application/pdf"
                              onChange={async (e) => {
                                const f = e.target.files?.[0];
                                if (f) await setRequiredAttachment(it.key, f);
                              }}
                              className="hidden"
                            />
                            <div className="px-3 py-2 border rounded bg-white">
                              Upload
                            </div>
                          </label>

                          {url ? (
                            <div className="flex items-center gap-2">
                              {url.endsWith(".pdf") ? (
                                <a
                                  className="text-sm underline"
                                  href={filePreview(url)}
                                  target="_blank"
                                  rel="noreferrer"
                                >
                                  View PDF
                                </a>
                              ) : (
                                <img
                                  alt={it.label}
                                  src={filePreview(url)}
                                  className="w-20 h-14 object-cover rounded border"
                                />
                              )}

                              <Button
                                size="sm"
                                variant="destructive"
                                onClick={async () => {
                                  await setRequiredAttachment(it.key, null);
                                }}
                              >
                                Remove
                              </Button>
                            </div>
                          ) : (
                            <div className="text-sm text-muted-foreground">
                              No file
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>

                {/* Optional attachments (multiple) */}
                <div>
                  <div className="mb-2 font-medium">Optional</div>

                  <div className="mb-3">
                    <div className="flex items-center justify-between mb-1">
                      <div className="text-sm">Pesticide Agreements</div>
                      <div className="text-xs text-muted-foreground">
                        optional
                      </div>
                    </div>
                    <div className="flex items-center gap-3 mb-2">
                      <input
                        type="file"
                        accept="image/*,application/pdf"
                        multiple
                        onChange={(e) =>
                          addOptionalFiles("agreements", e.target.files)
                        }
                      />
                    </div>

                    <div className="flex flex-wrap gap-2">
                      {form.attachments?.optional?.agreements?.map((u, idx) => (
                        <div
                          key={idx}
                          className="flex items-center gap-2 border rounded p-2"
                        >
                          {u.endsWith(".pdf") ? (
                            <a
                              href={filePreview(u)}
                              target="_blank"
                              rel="noreferrer"
                              className="text-sm underline"
                            >
                              PDF
                            </a>
                          ) : (
                            <img
                              src={filePreview(u)}
                              alt="agreements"
                              className="w-20 h-14 object-cover rounded"
                            />
                          )}
                          <Button
                            size="sm"
                            variant="destructive"
                            onClick={() =>
                              removeOptionalAttachment("agreements", idx)
                            }
                          >
                            Remove
                          </Button>
                        </div>
                      ))}
                      {(!form.attachments?.optional?.agreements ||
                        form.attachments.optional.agreements.length === 0) && (
                        <div className="text-sm text-muted-foreground">
                          No agreements uploaded
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="mb-3">
                    <div className="flex items-center justify-between mb-1">
                      <div className="text-sm">Other attachments</div>
                      <div className="text-xs text-muted-foreground">
                        optional
                      </div>
                    </div>
                    <div className="flex items-center gap-3 mb-2">
                      <input
                        type="file"
                        accept="image/*,application/pdf"
                        multiple
                        onChange={(e) =>
                          addOptionalFiles("others", e.target.files)
                        }
                      />
                    </div>

                    <div className="flex flex-wrap gap-2">
                      {form.attachments?.optional?.others?.map((u, idx) => (
                        <div
                          key={idx}
                          className="flex items-center gap-2 border rounded p-2"
                        >
                          {u.endsWith(".pdf") ? (
                            <a
                              href={filePreview(u)}
                              target="_blank"
                              rel="noreferrer"
                              className="text-sm underline"
                            >
                              PDF
                            </a>
                          ) : (
                            <img
                              src={filePreview(u)}
                              alt="other"
                              className="w-20 h-14 object-cover rounded"
                            />
                          )}
                          <Button
                            size="sm"
                            variant="destructive"
                            onClick={() =>
                              removeOptionalAttachment("others", idx)
                            }
                          >
                            Remove
                          </Button>
                        </div>
                      ))}
                      {(!form.attachments?.optional?.others ||
                        form.attachments.optional.others.length === 0) && (
                        <div className="text-sm text-muted-foreground">
                          No other files uploaded
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Sticky Footer */}
            <div className="sticky bottom-0 bg-background border-t pt-4 flex justify-end gap-2 pb-4">
              <Button
                variant="ghost"
                onClick={async () => {
                  setOpen(false);
                  // cleanup uploaded temp files (if any)
                  await cleanupTempFiles();
                  resetModalForm();
                }}
                type="button"
              >
                Cancel
              </Button>
              <Button type="submit">{editing ? "Save" : "Create"}</Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default DealerAddEditModal;
